version: '3.8'

services:
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./laravel:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:your-app-key
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root

  mojolicious:
    build:
      context: ./mojolicious
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./mojolicious:/usr/src/app
      - ./laravel:/var/www/html


#   db:
#     image: mysql:8.0
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: laravel
#       MYSQL_USER: root
#       MYSQL_PASSWORD: root
#     volumes:
#       - db_data:/var/lib/mysql

# volumes:
#   db_data: